import type { LibraryExercise } from "./types";

export const MUSCLE_GROUPS = [
  "Chest",
  "Upper Back",
  "Lats",
  "Lower Back",
  "Traps",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Forearms",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Core",
] as const;

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// Built-in ids are `builtin-<name-slug>`, so the list is freely orderable. The one
// rule: never rename a built-in in place — the slug (and thus its id) would change
// and detach existing history. Add a new entry instead.
const SEED: Array<[string, string[]]> = [
  // Legs
  ["Abductor Machine", ["Glutes"]],
  ["Adductor Machine", ["Quads", "Glutes"]],
  ["Back Squat", ["Quads", "Glutes"]],
  ["Belt Squat", ["Quads", "Glutes"]],
  ["Box Squat", ["Quads", "Glutes"]],
  ["Bulgarian Split Squat", ["Quads", "Glutes"]],
  ["Cable Kickback", ["Glutes"]],
  ["Cable Pull-Through", ["Glutes", "Hamstrings"]],
  ["Calf Raise", ["Calves"]],
  ["Cyclist Squat", ["Quads"]],
  ["Deadlift", ["Hamstrings", "Glutes", "Lower Back"]],
  ["Deficit Deadlift", ["Hamstrings", "Glutes", "Lower Back"]],
  ["Donkey Calf Raise", ["Calves"]],
  ["Front Squat", ["Quads", "Core"]],
  ["Glute Bridge", ["Glutes"]],
  ["Glute Kickback Machine", ["Glutes"]],
  ["Glute-Ham Raise", ["Hamstrings", "Glutes"]],
  ["Goblet Squat", ["Quads", "Glutes"]],
  ["Good Morning", ["Hamstrings", "Lower Back"]],
  ["Hack Squat", ["Quads", "Glutes"]],
  ["Hip Abduction", ["Glutes"]],
  ["Hip Adduction", ["Glutes", "Quads"]],
  ["Hip Thrust", ["Glutes", "Hamstrings"]],
  ["Iso-Lateral Leg Press", ["Quads", "Glutes"]],
  ["Landmine Squat", ["Quads", "Glutes"]],
  ["Leg Curl", ["Hamstrings"]],
  ["Leg Extension", ["Quads"]],
  ["Leg Press", ["Quads", "Glutes"]],
  ["Leg Press Calf Raise", ["Calves"]],
  ["Lying Leg Curl", ["Hamstrings"]],
  ["Nordic Curl", ["Hamstrings"]],
  ["Pendulum Squat", ["Quads", "Glutes"]],
  ["Reverse Hyperextension", ["Glutes", "Lower Back", "Hamstrings"]],
  ["Reverse Lunge", ["Quads", "Glutes"]],
  ["Reverse Nordic Curl", ["Quads"]],
  ["Romanian Deadlift", ["Hamstrings", "Glutes"]],
  ["Seated Calf Raise", ["Calves"]],
  ["Seated Leg Curl", ["Hamstrings"]],
  ["Single-Leg Leg Press", ["Quads", "Glutes"]],
  ["Sissy Squat", ["Quads"]],
  ["Smith Machine Calf Raise", ["Calves"]],
  ["Smith Machine Squat", ["Quads", "Glutes"]],
  ["Split Squat", ["Quads", "Glutes"]],
  ["Standing Calf Raise", ["Calves"]],
  ["Standing Leg Curl", ["Hamstrings"]],
  ["Step-Up", ["Quads", "Glutes"]],
  ["Stiff-Leg Deadlift", ["Hamstrings", "Glutes"]],
  ["Sumo Deadlift", ["Glutes", "Hamstrings", "Quads"]],
  ["Tibialis Raise", ["Calves"]],
  ["Trap Bar Deadlift", ["Quads", "Glutes", "Hamstrings"]],
  ["V-Squat", ["Quads", "Glutes"]],
  ["Walking Lunge", ["Quads", "Glutes"]],
  ["Zercher Squat", ["Quads", "Glutes", "Core"]],

  // Chest
  ["Bench Press", ["Chest", "Triceps"]],
  ["Cable Crossover", ["Chest"]],
  ["Cable Fly", ["Chest"]],
  ["Chest Fly", ["Chest"]],
  ["Decline Bench Press", ["Chest", "Triceps"]],
  ["Dumbbell Bench Press", ["Chest", "Triceps"]],
  ["Dumbbell Fly", ["Chest"]],
  ["High-to-Low Cable Fly", ["Chest"]],
  ["Incline Bench Press", ["Chest", "Shoulders"]],
  ["Incline Cable Fly", ["Chest"]],
  ["Incline Dumbbell Press", ["Chest", "Shoulders"]],
  ["Incline Machine Press", ["Chest", "Shoulders"]],
  ["Iso-Lateral Chest Press", ["Chest", "Triceps"]],
  ["Iso-Lateral Incline Press", ["Chest", "Shoulders"]],
  ["Low-to-High Cable Fly", ["Chest"]],
  ["Machine Chest Press", ["Chest", "Triceps"]],
  ["Machine Decline Press", ["Chest", "Triceps"]],
  ["Pec Deck", ["Chest"]],
  ["Push-Up", ["Chest", "Triceps"]],
  ["Smith Machine Bench Press", ["Chest", "Triceps"]],
  ["Smith Machine Incline Press", ["Chest", "Shoulders"]],
  ["Svend Press", ["Chest"]],
  ["Weighted Dip", ["Chest", "Triceps"]],

  // Back
  ["Assisted Pull-Up", ["Lats", "Biceps"]],
  ["Back Extension", ["Lower Back", "Glutes"]],
  ["Barbell Row", ["Upper Back", "Lats"]],
  ["Barbell Shrug", ["Traps"]],
  ["Cable Pullover", ["Lats"]],
  ["Chest-Supported Row", ["Upper Back", "Lats"]],
  ["Chin-Up", ["Lats", "Biceps"]],
  ["Dumbbell Row", ["Lats", "Upper Back"]],
  ["Dumbbell Shrug", ["Traps"]],
  ["Face Pull", ["Upper Back", "Shoulders"]],
  ["Gorilla Row", ["Lats", "Upper Back"]],
  ["Inverted Row", ["Upper Back", "Lats"]],
  ["Iso-Lateral Low Row", ["Upper Back", "Lats"]],
  ["Iso-Lateral Pulldown", ["Lats", "Biceps"]],
  ["Iso-Lateral Row", ["Upper Back", "Lats"]],
  ["Kroc Row", ["Lats", "Upper Back"]],
  ["Landmine Row", ["Upper Back", "Lats"]],
  ["Lat Pulldown", ["Lats", "Biceps"]],
  ["Machine High Row", ["Upper Back", "Lats"]],
  ["Machine Pullover", ["Lats"]],
  ["Machine Row", ["Upper Back", "Lats"]],
  ["Meadows Row", ["Upper Back", "Lats"]],
  ["Neutral-Grip Pull-Up", ["Lats", "Biceps"]],
  ["Pendlay Row", ["Upper Back", "Lats"]],
  ["Pull-Up", ["Lats", "Biceps"]],
  ["Rack Pull", ["Lower Back", "Traps", "Glutes"]],
  ["Seal Row", ["Upper Back", "Lats"]],
  ["Seated Cable Row", ["Upper Back", "Lats"]],
  ["Single-Arm Lat Pulldown", ["Lats"]],
  ["Straight-Arm Pulldown", ["Lats"]],
  ["T-Bar Row", ["Upper Back", "Lats"]],
  ["Wide-Grip Lat Pulldown", ["Lats"]],

  // Shoulders
  ["Arnold Press", ["Shoulders", "Triceps"]],
  ["Behind-the-Neck Press", ["Shoulders", "Triceps"]],
  ["Bradford Press", ["Shoulders"]],
  ["Cable Front Raise", ["Shoulders"]],
  ["Cable Lateral Raise", ["Shoulders"]],
  ["Cable Rear Delt Fly", ["Shoulders", "Upper Back"]],
  ["Cable Upright Row", ["Shoulders", "Traps"]],
  ["Dumbbell Shoulder Press", ["Shoulders", "Triceps"]],
  ["Front Raise", ["Shoulders"]],
  ["Iso-Lateral Shoulder Press", ["Shoulders", "Triceps"]],
  ["Landmine Press", ["Shoulders", "Chest"]],
  ["Lateral Raise", ["Shoulders"]],
  ["Machine Lateral Raise", ["Shoulders"]],
  ["Machine Shoulder Press", ["Shoulders", "Triceps"]],
  ["Overhead Press", ["Shoulders", "Triceps"]],
  ["Push Press", ["Shoulders", "Triceps"]],
  ["Rear Delt Fly", ["Shoulders", "Upper Back"]],
  ["Reverse Pec Deck", ["Shoulders", "Upper Back"]],
  ["Upright Row", ["Shoulders", "Traps"]],
  ["Viking Press", ["Shoulders", "Triceps"]],
  ["Y-Raise", ["Shoulders", "Upper Back"]],

  // Arms
  ["Assisted Dip", ["Triceps", "Chest"]],
  ["Barbell Curl", ["Biceps"]],
  ["Bayesian Curl", ["Biceps"]],
  ["Bench Dip", ["Triceps"]],
  ["Cable Curl", ["Biceps"]],
  ["Cable Hammer Curl", ["Biceps", "Forearms"]],
  ["Close-Grip Bench Press", ["Triceps", "Chest"]],
  ["Concentration Curl", ["Biceps"]],
  ["Cross-Body Hammer Curl", ["Biceps", "Forearms"]],
  ["Diamond Push-Up", ["Triceps", "Chest"]],
  ["Dip", ["Triceps", "Chest"]],
  ["Drag Curl", ["Biceps"]],
  ["Dumbbell Curl", ["Biceps"]],
  ["Dumbbell Kickback", ["Triceps"]],
  ["EZ-Bar Curl", ["Biceps"]],
  ["Hammer Curl", ["Biceps", "Forearms"]],
  ["Incline Dumbbell Curl", ["Biceps"]],
  ["JM Press", ["Triceps"]],
  ["Machine Dip", ["Triceps", "Chest"]],
  ["Machine Preacher Curl", ["Biceps"]],
  ["Machine Triceps Extension", ["Triceps"]],
  ["Overhead Cable Extension", ["Triceps"]],
  ["Overhead Triceps Extension", ["Triceps"]],
  ["Preacher Curl", ["Biceps"]],
  ["Rope Pushdown", ["Triceps"]],
  ["Skull Crusher", ["Triceps"]],
  ["Spider Curl", ["Biceps"]],
  ["Tate Press", ["Triceps"]],
  ["Triceps Pushdown", ["Triceps"]],
  ["Zottman Curl", ["Biceps", "Forearms"]],

  // Forearms
  ["Behind-the-Back Wrist Curl", ["Forearms"]],
  ["Farmer's Carry", ["Forearms", "Traps", "Core"]],
  ["Plate Pinch", ["Forearms"]],
  ["Reverse Curl", ["Forearms", "Biceps"]],
  ["Reverse Wrist Curl", ["Forearms"]],
  ["Wrist Curl", ["Forearms"]],
  ["Wrist Roller", ["Forearms"]],

  // Core
  ["Ab Wheel Rollout", ["Core"]],
  ["Cable Crunch", ["Core"]],
  ["Cable Woodchopper", ["Core"]],
  ["Crunch", ["Core"]],
  ["Dead Bug", ["Core"]],
  ["Decline Sit-Up", ["Core"]],
  ["Hanging Leg Raise", ["Core"]],
  ["Hollow Hold", ["Core"]],
  ["Leg Raise", ["Core"]],
  ["Machine Crunch", ["Core"]],
  ["Mountain Climber", ["Core"]],
  ["Pallof Press", ["Core"]],
  ["Plank", ["Core"]],
  ["Russian Twist", ["Core"]],
  ["Side Plank", ["Core"]],
  ["Sit-Up", ["Core"]],
  ["Toes-to-Bar", ["Core"]],
  ["Weighted Crunch", ["Core"]],
];

export function defaultLibrary(): LibraryExercise[] {
  return SEED.map(([name, muscleGroups]) => ({
    id: `builtin-${slug(name)}`,
    name,
    muscleGroups,
    custom: false,
  }));
}
